### PR TITLE
Allow nelmio/alice 2.1.0

### PR DESCRIPTION
**Pull request by enumag**
https://github.com/nelmio/alice/releases/tag/2.1.0

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I guess `~2.1` could be fine. The package is reliable. Could you change that please?

**Comment by enumag** [comment]
Why not `~2.0`?

**Comment by TomasVotruba** [comment]
Yea, sorry, that's what I meant.

**Comment by enumag** [comment]
Done, although maybe we should remove the `.0` from all dependencies. This package only uses the basic stuff from all of them so it should be save.

**Comment by TomasVotruba** [comment]
Great idea. I probably made that change after bad experience with Nette 2.3 dependencies conflicts.
Should be ok on. Could you integrate it to this PR?

**Comment by enumag** [comment]
Done.

**Comment by TomasVotruba** [comment]
Awesome, thank you!

**Pull request merged**
